version: "3"
services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - makaron

  postgresql:
    image: "postgres:12.1"
    ports:
    - "8081:5432"
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=makaronshick
      - POSTGRES_PASSWORD=123
    networks:
      - makaron

  adminer:
    image: "adminer:4.7.5"
    ports:
    - "8082:8080"
    networks:
      - makaron

networks:
  makaron:
